source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
pod 'SwiftGraph','1.0'
pod 'BEMSimpleLineGraph','4.0'
pod 'EZAudio','1.0.1'
pod 'KDCircularProgress','1.1'
pod 'Alamofire','1.2.3'
pod 'SwiftyJSON','2.2.0'
pod 'XLForm','3.0.0'
pod 'DrawerController','1.0.4'
pod 'HTPressableButton','1.3.2'
